<?php

/**
 * UserIdentity represents the data needed to identity a user.
 * It contains the authentication method that checks if the provided
 * data can identity the user.
 */
class UserIdentity extends CUserIdentity
{
    public function authenticate()
    {
        parent::authenticate(); // TODO: Change the autogenerated stub
    }

    public function authenticateAdmin(){
        $admin = Administrador::model()->findByAttributes(array('email'=>$this->username));
        if(!is_object($admin))
            $this->errorCode = self::ERROR_USERNAME_INVALID;
        else{
            $user = Users::model()->findByPk($admin->user);
            if($this->authenticateUser($user)){
                $this->setState('user__id', $admin->id);
                $this->setState('user__email', $admin->email);
                $this->setState('user__name', $admin->nombre);
            }
        }

        return !$this->errorCode;
    }

    private function authenticateUser($user){
        if(!is_object($user)){
            $this->errorCode = self::ERROR_USERNAME_INVALID;
            return false;
        }
        else if(crypt($this->password, $user->password) != $user->password){
            $this->errorCode = self::ERROR_PASSWORD_INVALID;
            return false;
        }
        else{
            $this->errorCode = self::ERROR_NONE;
            return true;
        }
    }
}